#
# This is an example configuration for riverbank.
#
# It is also used for integration testing of riverbank itself
---
shares:
  - name: rtyler
    schemas:
      - name: samples
        tables:
          - name: covid19-nyt
            #location: 's3://delta-riverbank/COVID-19_NYT'
            location: 's3://data/COVID-19_NYT'

  - name: vaccine_share
    schemas:
      - name: acme_vaccine_data
        tables:
          - name: vaccine_ingredients
            location: 's3://delta/acme_vaccine_data/vaccine_ingredients'

